local colors = require("colors")

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "ghostty"
local fileManager = "dolphin"
local menu        = "walker"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")

    -- System services
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland && systemctl --user start hyprland-session.target")
    hl.exec_cmd("kbuildsycoca6")

    -- Desktop environment
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprlock")

    -- Launcher backend
    hl.exec_cmd("elephant")
    hl.exec_cmd("sleep 2 && walker --gapplication-service")

    -- Apps
    hl.exec_cmd("discord")
    hl.exec_cmd("zen-browser")
    hl.exec_cmd("steam")
    hl.exec_cmd("heroic")
    hl.exec_cmd("cider")

end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("XDG_MENU_PREFIX", "arch-")
local is_gaming = false

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 8,

        border_size = 2,

        col = {
            active_border   = "rgba(" .. colors.accent:sub(5) .. "ee)",
            inactive_border = "rgba(" .. colors.border:sub(5) .. "aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 0,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 0.96,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 8,
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 8,
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding       = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding       = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
	natural_scroll = true,
        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier


-- Applications
hl.bind("SUPER + RETURN",      hl.dsp.exec_cmd(terminal),                	                   { description = "Terminal" })
hl.bind("SUPER + E",           hl.dsp.exec_cmd(fileManager),                                       { description = "File manager" })
hl.bind("SUPER + SPACE",       hl.dsp.exec_cmd(menu),                                              { description = "Launcher" })
hl.bind("SUPER + ALT + SPACE", hl.dsp.exec_cmd("~/.local/bin/sys-menu"),                           { description = "System menu" })
hl.bind("F6", 		       hl.dsp.exec_cmd("~/.config/scripts/autoclicker-toggle.py --start"), { transparent = true, ignore_mods = true, description = "Start autoclicker (press)" })
hl.bind("F6", 		       hl.dsp.exec_cmd("~/.config/scripts/autoclicker-toggle.py --stop"),  { release = true, transparent = true, ignore_mods = true, description = "Stop autoclicker (release)" })

-- Windows
local closeWindowBind = hl.bind("SUPER + W", hl.dsp.window.close(),        			     { description = "Close window" })
hl.bind("SUPER + T",           hl.dsp.window.float({ action = "toggle" }), 			     { description = "Float toggle" })
hl.bind("SUPER + P",           hl.dsp.window.pseudo(),                      		      	     { description = "Pseudo window" })
hl.bind("SUPER + J",           hl.dsp.layout("togglesplit"),               			     { description = "Toggle split" })
hl.bind("SUPER + F",           hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Fullscreen" })
hl.bind("SUPER + ALT + F",     hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }),  { description = "Maximize" })
 
-- Focus
hl.bind("SUPER + left",        hl.dsp.focus({ direction = "left" }),         { description = "Focus left" })
hl.bind("SUPER + right",       hl.dsp.focus({ direction = "right" }),        { description = "Focus right" })
hl.bind("SUPER + up",          hl.dsp.focus({ direction = "up" }),           { description = "Focus up" })
hl.bind("SUPER + down",        hl.dsp.focus({ direction = "down" }),         { description = "Focus down" })
 
-- Workspaces
for i = 1, 10 do
    local key = i % 10
    hl.bind("SUPER + " .. key,         hl.dsp.focus({ workspace = i }),              { description = "Switch to workspace " .. i })
    hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }),        { description = "Move window to workspace " .. i })
end
 
-- Special workspace (scratchpad)
hl.bind("SUPER + Z",           hl.dsp.workspace.toggle_special("magic"),            { description = "Toggle scratchpad" })
hl.bind("SUPER + SHIFT + Z",   hl.dsp.window.move({ workspace = "special:magic" }), { description = "Move window to scratchpad" })
 
-- Scroll workspaces
hl.bind("SUPER + mouse_down",  hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind("SUPER + mouse_up",    hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })
 
-- Mouse window management
hl.bind("SUPER + mouse:272", function()
    local f = io.open("/tmp/hypr-gamemode", "r")
    if f then
        io.close(f)
    else
        hl.dispatch(hl.dsp.window.drag())
    end
end, { mouse = true, description = "Move window" })
hl.bind("SUPER + mouse:273", function()
    local f = io.open("/tmp/hypr-gamemode", "r")
    if f then
        io.close(f)
    else
        hl.dispatch(hl.dsp.window.resize())
    end
end, { mouse = true, description = "Resize window" })
 
-- System
hl.bind("SUPER + M", hl.dsp.exec_cmd("hyprlock"), { description = "Lock screen" })
 
-- Touchbar: Display brightness
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("my-touchbar-controller display 5%-"),  { locked = true, repeating = true, description = "Brightness down" })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("my-touchbar-controller display +5%"),  { locked = true, repeating = true, description = "Brightness up" })
 
-- Touchbar: Keyboard backlight
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("my-touchbar-controller keyboard 10%-"), { locked = true, repeating = true, description = "Keyboard brightness down" })
hl.bind("XF86KbdBrightnessUp",   hl.dsp.exec_cmd("my-touchbar-controller keyboard +10%"), { locked = true, repeating = true, description = "Keyboard brightness up" })
 
-- Touchbar: Audio
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("my-touchbar-controller audio --input-volume mute-toggle"),  { locked = true, description = "Mute microphone" })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("my-touchbar-controller audio --output-volume mute-toggle"), { locked = true, description = "Mute" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("my-touchbar-controller audio --output-volume lower"),       { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("my-touchbar-controller audio --output-volume raise"),       { locked = true, repeating = true, description = "Volume up" })
 
-- Touchbar: Media
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("my-touchbar-controller media previous"),   { locked = true, description = "Previous track" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("my-touchbar-controller media play-pause"), { locked = true, description = "Pause" })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("my-touchbar-controller media play-pause"), { locked = true, description = "Play" })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("my-touchbar-controller media next"),       { locked = true, description = "Next track" })
 
-- Universal clipboard
-- Workaround for Hyprland synthetic key state bug:
-- https://github.com/hyprwm/Hyprland/discussions/14099
local function send_shortcut_once(mods, key)
  return function()
    hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "down", window = "activewindow" }))
    hl.timer(function()
      hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up", window = "activewindow" }))
    end, { timeout = 50, type = "oneshot" })
  end
end
 
hl.bind("SUPER + C",      send_shortcut_once("CTRL", "Insert"),  { description = "Copy" })
hl.bind("SUPER + V",      send_shortcut_once("SHIFT", "Insert"), { description = "Paste" })
hl.bind("SUPER + X",      send_shortcut_once("CTRL", "X"),       { description = "Cut" })
 
-- Clipboard history
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("walker -m clipboard"),    { description = "Clipboard history" })
 
-- Keybindings viewer
hl.bind("SUPER + K", hl.dsp.exec_cmd("/home/felix/.local/bin/keybindings"),     { description = "Show keybindings" })
 
-- Screenshots
hl.bind("SUPER + S", hl.dsp.exec_cmd([[
    FILE=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && \
    grimblast --freeze save area "$FILE" && \
    [ "$(notify-send 'Screenshot Captured' 'Click to edit selection' -i "$FILE" --action='default=Edit')" = "default" ] && satty -f "$FILE"
]]), { description = "Screenshot region" })
 
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd([[
    FILE=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && \
    grimblast save output "$FILE" && \
    [ "$(notify-send 'Screen Captured' 'Click to edit capture' -i "$FILE" --action='default=Edit')" = "default" ] && satty -f "$FILE"
]]), { description = "Screenshot screen" })

-- Gamemode toggle
hl.bind("SUPER + F12", hl.dsp.exec_cmd("/home/felix/.config/scripts/gamemode.sh"), { description = "Gamemode toggle" })

-- Gamemode submap
hl.define_submap("gamemode", function()
    is_gaming = true


    hl.bind("SUPER + F12", function()
        is_gaming = false

        hl.exec_cmd("/home/felix/.config/scripts/gamemode.sh")
    end, { description = "Exit gamemode" })

    hl.bind("SUPER + K", hl.dsp.exec_cmd("/home/felix/.local/bin/keybindings"),                 { description = "Show keybindings" })
    hl.bind("F6", hl.dsp.exec_cmd("/home/felix/.config/scripts/autoclicker-toggle.py --start"), { repeating = false, transparent = true, ignore_mods = true, description = "Start autoclicker (press)" })
    hl.bind("F6", hl.dsp.exec_cmd("/home/felix/.config/scripts/autoclicker-toggle.py --stop"),  { release = true, transparent = true, ignore_mods = true, description = "Stop autoclicker (release)" })

    -- Keep media/brightness/audio keys working
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("my-touchbar-controller display 5%-"),                   { locked = true, repeating = true, description = "Brightness down" })
    hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("my-touchbar-controller display +5%"),                   { locked = true, repeating = true, description = "Brightness up" })
    hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("my-touchbar-controller keyboard 10%-"),                 { locked = true, repeating = true, description = "Keyboard brightness down" })
    hl.bind("XF86KbdBrightnessUp",   hl.dsp.exec_cmd("my-touchbar-controller keyboard +10%"),                 { locked = true, repeating = true, description = "Keyboard brightness up" })
    hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("my-touchbar-controller audio --input-volume mute-toggle"),  { locked = true, description = "Mute mic" })
    hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("my-touchbar-controller audio --output-volume mute-toggle"), { locked = true, description = "Mute audio" })
    hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("my-touchbar-controller audio --output-volume lower"),       { locked = true, repeating = true, description = "Volume down" })
    hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("my-touchbar-controller audio --output-volume raise"),       { locked = true, repeating = true, description = "Volume up" })
    hl.bind("XF86AudioPrev",         hl.dsp.exec_cmd("my-touchbar-controller media previous"),                    { locked = true, description = "Previous track" })
    hl.bind("XF86AudioPause",        hl.dsp.exec_cmd("my-touchbar-controller media play-pause"),                  { locked = true, description = "Play/pause" })
    hl.bind("XF86AudioPlay",         hl.dsp.exec_cmd("my-touchbar-controller media play-pause"),                  { locked = true, description = "Play/pause" })
    hl.bind("XF86AudioNext",         hl.dsp.exec_cmd("my-touchbar-controller media next"),                        { locked = true, description = "Next track" })
end)

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Window rules: open apps on specific workspaces
hl.window_rule({ name = "zen-ws",     match = { class = "zen" },                    workspace = "1" })
hl.window_rule({ name = "discord-ws", match = { class = "discord" },                workspace = "2" })
hl.window_rule({ name = "gaming-ws",  match = { class = "(steam|heroic)" },         workspace = "3" })
hl.window_rule({ name = "obs-ws",     match = { class = "com.obsproject.Studio" },  workspace = "4" })
hl.window_rule({ name = "cider-ws",   match = { class = "cider" },                  workspace = "5" })

-- Workspace rules: assign workspaces to monitors
hl.workspace_rule({ workspace = "1", monitor = "DP-2", default = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-2" })
hl.workspace_rule({ workspace = "3", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "4", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "5", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "6", monitor = "eDP-1", default = true })

hl.window_rule({
    match = { class = "org.omarchy.screensaver" },
    float = true,
    fullscreen = true
})

hl.window_rule({
  name = "float-autoclicker",
  match = { class = "^(dev.felix.autoclicker)$" },
  float = true,
})
