wallpaper {
    monitor = eDP-1
    path = /home/felix/.local/share/wallpapers/custom-wallpapers/dark-waters.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/felix/.local/share/wallpapers/custom-wallpapers/dark-waters.jpg
    fit_mode = cover
}

splash = false
ipc = on
