context.modules = [
  {
    name = libpipewire-module-filter-chain
    flags = [ nofail ]
    args = {
      audio.channels   = 1
      audio.position   = [ MONO ]
      node.description = "Boosted Builtin Mic"
      media.name       = "Boosted Builtin Mic"
      filter.graph = {
        nodes = [
          {
            type    = ladspa
            name    = gain
            plugin  = amp
            label   = amp_mono
            control = { "Gain" = 150.0 }
          }
        ]
        inputs  = [ "gain:Input" ]
        outputs = [ "gain:Output" ]
      }
      capture.props = {
        node.name         = "effect_input.mic_boost"
        node.target       = "alsa_input.pci-0000_04_00.3.BuiltinMic"
        node.passive      = false
      }
      playback.props = {
        node.name   = "effect_output.mic_boost"
        media.class = "Audio/Source"
      }
    }
  }
]
