monitor.bluez.rules = [
  {
    matches = [
      {
        # Priority 1 Output: Mpow H17
        node.name = "~bluez_output.02_1A_01_14_DE_73.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 2500
        priority.session = 2500
      }
    }
  },
  {
    matches = [
      {
        # Priority 2 Output: AirPods Pro
        node.name = "~bluez_output.40_B3_FA_50_1F_41.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1800
        priority.session = 1800
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      {
        # Hard Hide: HDMI audio profiles
        node.name = "~alsa_output.*hdmi*"
      },
      {
        # Hard Hide: Wired Headphone Jack
        node.name = "~alsa_output.pci-0000_04_00.3.*Headphones*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },
  {
    matches = [
      {
        # Priority 3 Output: Built-in Apple Speakers
        node.name = "~alsa_output.pci-0000_04_00.3.*Speakers*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1000
        priority.session = 1000
      }
    }
  },
  {
    matches = [
      {
        # Priority 4 Output: USB PnP
        node.name = "~alsa_output.usb-*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 500
        priority.session = 500
      }
    }
  },
  {
    matches = [
      {
        # Priority 2 Input: Built-in Mic
        node.name = "~alsa_input.pci-0000_04_00.3.*BuiltinMic*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1000
        priority.session = 1000
      }
    }
  },
  {
    matches = [
      {
        # Priority 3 Input: USB PnP Mic
        node.name = "~alsa_input.usb-*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 500
        priority.session = 500
      }
    }
  }
]
